services:
  backend:
    container_name: QtubeBackend
    restart: always

    build:
      context: .
      dockerfile: Dockerfile.prod

    ports:
      - "8081:8081" # Changed to 8081 as per instruction

    env_file:
      - ./.env
    
    depends_on:
      - q_redis
      - q_postgres

    command: sh -c "/app/node_modules/.bin/pm2-runtime start ecosystem.config.js"
    networks:
      - app-network-group

  q_redis:
    image: redis:7-alpine
    container_name: q_redis
    command:
      - redis-server
      - --notify-keyspace-events
      - Ex
    restart: always
    ports:
      - "6379:6379"

    networks:
      - app-network-group

  q_postgres:
    image: postgres:17
    container_name: q_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=q_postgres
      - POSTGRES_PASSWORD=qtube_super_secret_password
      - POSTGRES_DB=qtube
    volumes:
      - qpgdata:/var/lib/postgresql/data
    networks:
      - app-network-group

volumes:
  qpgdata:

networks:
  app-network-group:
